// AUTO-GENERATED by scripts/gen-species.mjs from PokéAPI base stats & types.
// Do not edit by hand — re-run the generator to refresh. Pure static data.
import type { TypeName } from './types';
import type { AbilityId } from './abilities';

export interface BaseStats {
  hp: number;
  atk: number;
  def: number;
  spd: number;
}

export interface Species {
  /** stable id (English lowercase) */
  name: string;
  /** national Pokédex number (used to build sprite URLs) */
  id: number;
  /** display label */
  label: string;
  /** 1-2 types, slot order preserved */
  types: TypeName[];
  /** official base stats */
  base: BaseStats;
  /** battle ability (shared across the evolution line) */
  ability: AbilityId;
  /** optional off-type coverage move */
  coverage?: TypeName;
}

/** Curated evolution lines (basic -> ... -> final). */
export const CHAINS: readonly string[][] = [
  ['charmander', 'charmeleon', 'charizard'],
  ['squirtle', 'wartortle', 'blastoise'],
  ['bulbasaur', 'ivysaur', 'venusaur'],
  ['treecko', 'grovyle', 'sceptile'],
  ['chimchar', 'monferno', 'infernape'],
  ['piplup', 'prinplup', 'empoleon'],
  ['ralts', 'kirlia', 'gardevoir'],
  ['gastly', 'haunter', 'gengar'],
  ['dratini', 'dragonair', 'dragonite'],
  ['larvitar', 'pupitar', 'tyranitar'],
  ['beldum', 'metang', 'metagross'],
  ['trapinch', 'vibrava', 'flygon'],
  ['swinub', 'piloswine', 'mamoswine'],
  ['machop', 'machoke', 'machamp'],
  ['abra', 'kadabra', 'alakazam'],
  ['shinx', 'luxio', 'luxray'],
  ['tympole', 'palpitoad', 'seismitoad'],
  ['zubat', 'golbat', 'crobat'],
  ['geodude', 'graveler', 'golem'],
  ['magikarp', 'gyarados'],
  ['magnemite', 'magneton'],
  ['scyther', 'scizor'],
  ['sandshrew', 'sandslash'],
  ['snorunt', 'glalie'],
  ['riolu', 'lucario'],
  ['tauros'],
  ['snorlax'],
  ['lapras'],
  ['aerodactyl'],
  ['skarmory'],
  ['absol'],
  ['mawile'],
];

export const SPECIES: Record<string, Species> = {
  charmander: { name: 'charmander', id: 4, label: 'Charmander', types: ['fire'], base: { hp: 39, atk: 52, def: 43, spd: 65 }, ability: 'guts' },
  charmeleon: { name: 'charmeleon', id: 5, label: 'Charmeleon', types: ['fire'], base: { hp: 58, atk: 64, def: 58, spd: 80 }, ability: 'guts' },
  charizard: { name: 'charizard', id: 6, label: 'Charizard', types: ['fire', 'flying'], base: { hp: 78, atk: 84, def: 78, spd: 100 }, ability: 'guts', coverage: 'dragon' },
  squirtle: { name: 'squirtle', id: 7, label: 'Squirtle', types: ['water'], base: { hp: 44, atk: 48, def: 65, spd: 43 }, ability: 'shell' },
  wartortle: { name: 'wartortle', id: 8, label: 'Wartortle', types: ['water'], base: { hp: 59, atk: 63, def: 80, spd: 58 }, ability: 'shell' },
  blastoise: { name: 'blastoise', id: 9, label: 'Blastoise', types: ['water'], base: { hp: 79, atk: 83, def: 100, spd: 78 }, ability: 'shell', coverage: 'ice' },
  bulbasaur: { name: 'bulbasaur', id: 1, label: 'Bulbasaur', types: ['grass', 'poison'], base: { hp: 45, atk: 49, def: 49, spd: 45 }, ability: 'regen' },
  ivysaur: { name: 'ivysaur', id: 2, label: 'Ivysaur', types: ['grass', 'poison'], base: { hp: 60, atk: 62, def: 63, spd: 60 }, ability: 'regen' },
  venusaur: { name: 'venusaur', id: 3, label: 'Venusaur', types: ['grass', 'poison'], base: { hp: 80, atk: 82, def: 83, spd: 80 }, ability: 'regen' },
  treecko: { name: 'treecko', id: 252, label: 'Treecko', types: ['grass'], base: { hp: 40, atk: 45, def: 35, spd: 70 }, ability: 'swift' },
  grovyle: { name: 'grovyle', id: 253, label: 'Grovyle', types: ['grass'], base: { hp: 50, atk: 65, def: 45, spd: 95 }, ability: 'swift' },
  sceptile: { name: 'sceptile', id: 254, label: 'Sceptile', types: ['grass'], base: { hp: 70, atk: 85, def: 65, spd: 120 }, ability: 'swift', coverage: 'dragon' },
  chimchar: { name: 'chimchar', id: 390, label: 'Chimchar', types: ['fire'], base: { hp: 44, atk: 58, def: 44, spd: 61 }, ability: 'guts' },
  monferno: { name: 'monferno', id: 391, label: 'Monferno', types: ['fire', 'fighting'], base: { hp: 64, atk: 78, def: 52, spd: 81 }, ability: 'guts' },
  infernape: { name: 'infernape', id: 392, label: 'Infernape', types: ['fire', 'fighting'], base: { hp: 76, atk: 104, def: 71, spd: 108 }, ability: 'guts', coverage: 'rock' },
  piplup: { name: 'piplup', id: 393, label: 'Piplup', types: ['water'], base: { hp: 53, atk: 51, def: 53, spd: 40 }, ability: 'shell' },
  prinplup: { name: 'prinplup', id: 394, label: 'Prinplup', types: ['water'], base: { hp: 64, atk: 66, def: 68, spd: 50 }, ability: 'shell' },
  empoleon: { name: 'empoleon', id: 395, label: 'Empoleon', types: ['water', 'steel'], base: { hp: 84, atk: 86, def: 88, spd: 60 }, ability: 'shell', coverage: 'ice' },
  ralts: { name: 'ralts', id: 280, label: 'Ralts', types: ['psychic', 'fairy'], base: { hp: 28, atk: 25, def: 25, spd: 40 }, ability: 'lucky' },
  kirlia: { name: 'kirlia', id: 281, label: 'Kirlia', types: ['psychic', 'fairy'], base: { hp: 38, atk: 35, def: 35, spd: 50 }, ability: 'lucky' },
  gardevoir: { name: 'gardevoir', id: 282, label: 'Gardevoir', types: ['psychic', 'fairy'], base: { hp: 68, atk: 65, def: 65, spd: 80 }, ability: 'lucky', coverage: 'ice' },
  gastly: { name: 'gastly', id: 92, label: 'Gastly', types: ['ghost', 'poison'], base: { hp: 30, atk: 35, def: 30, spd: 80 }, ability: 'drain' },
  haunter: { name: 'haunter', id: 93, label: 'Haunter', types: ['ghost', 'poison'], base: { hp: 45, atk: 50, def: 45, spd: 95 }, ability: 'drain' },
  gengar: { name: 'gengar', id: 94, label: 'Gengar', types: ['ghost', 'poison'], base: { hp: 60, atk: 65, def: 60, spd: 110 }, ability: 'drain', coverage: 'fighting' },
  dratini: { name: 'dratini', id: 147, label: 'Dratini', types: ['dragon'], base: { hp: 41, atk: 64, def: 45, spd: 50 }, ability: 'intimidate' },
  dragonair: { name: 'dragonair', id: 148, label: 'Dragonair', types: ['dragon'], base: { hp: 61, atk: 84, def: 65, spd: 70 }, ability: 'intimidate' },
  dragonite: { name: 'dragonite', id: 149, label: 'Dragonite', types: ['dragon', 'flying'], base: { hp: 91, atk: 134, def: 95, spd: 80 }, ability: 'intimidate', coverage: 'fire' },
  larvitar: { name: 'larvitar', id: 246, label: 'Larvitar', types: ['rock', 'ground'], base: { hp: 50, atk: 64, def: 50, spd: 41 }, ability: 'shell' },
  pupitar: { name: 'pupitar', id: 247, label: 'Pupitar', types: ['rock', 'ground'], base: { hp: 70, atk: 84, def: 70, spd: 51 }, ability: 'shell' },
  tyranitar: { name: 'tyranitar', id: 248, label: 'Tyranitar', types: ['rock', 'dark'], base: { hp: 100, atk: 134, def: 110, spd: 61 }, ability: 'shell', coverage: 'fire' },
  beldum: { name: 'beldum', id: 374, label: 'Beldum', types: ['steel', 'psychic'], base: { hp: 40, atk: 55, def: 80, spd: 30 }, ability: 'focus' },
  metang: { name: 'metang', id: 375, label: 'Metang', types: ['steel', 'psychic'], base: { hp: 60, atk: 75, def: 100, spd: 50 }, ability: 'focus' },
  metagross: { name: 'metagross', id: 376, label: 'Metagross', types: ['steel', 'psychic'], base: { hp: 80, atk: 135, def: 130, spd: 70 }, ability: 'focus', coverage: 'ground' },
  trapinch: { name: 'trapinch', id: 328, label: 'Trapinch', types: ['ground'], base: { hp: 45, atk: 100, def: 45, spd: 10 }, ability: 'swift' },
  vibrava: { name: 'vibrava', id: 329, label: 'Vibrava', types: ['ground', 'dragon'], base: { hp: 50, atk: 70, def: 50, spd: 70 }, ability: 'swift' },
  flygon: { name: 'flygon', id: 330, label: 'Flygon', types: ['ground', 'dragon'], base: { hp: 80, atk: 100, def: 80, spd: 100 }, ability: 'swift', coverage: 'fire' },
  swinub: { name: 'swinub', id: 220, label: 'Swinub', types: ['ice', 'ground'], base: { hp: 50, atk: 50, def: 40, spd: 50 }, ability: 'guts' },
  piloswine: { name: 'piloswine', id: 221, label: 'Piloswine', types: ['ice', 'ground'], base: { hp: 100, atk: 100, def: 80, spd: 50 }, ability: 'guts' },
  mamoswine: { name: 'mamoswine', id: 473, label: 'Mamoswine', types: ['ice', 'ground'], base: { hp: 110, atk: 130, def: 80, spd: 80 }, ability: 'guts', coverage: 'rock' },
  machop: { name: 'machop', id: 66, label: 'Machop', types: ['fighting'], base: { hp: 70, atk: 80, def: 50, spd: 35 }, ability: 'guts' },
  machoke: { name: 'machoke', id: 67, label: 'Machoke', types: ['fighting'], base: { hp: 80, atk: 100, def: 70, spd: 45 }, ability: 'guts' },
  machamp: { name: 'machamp', id: 68, label: 'Machamp', types: ['fighting'], base: { hp: 90, atk: 130, def: 80, spd: 55 }, ability: 'guts', coverage: 'rock' },
  abra: { name: 'abra', id: 63, label: 'Abra', types: ['psychic'], base: { hp: 25, atk: 20, def: 15, spd: 90 }, ability: 'focus' },
  kadabra: { name: 'kadabra', id: 64, label: 'Kadabra', types: ['psychic'], base: { hp: 40, atk: 35, def: 30, spd: 105 }, ability: 'focus' },
  alakazam: { name: 'alakazam', id: 65, label: 'Alakazam', types: ['psychic'], base: { hp: 55, atk: 50, def: 45, spd: 120 }, ability: 'focus', coverage: 'fighting' },
  shinx: { name: 'shinx', id: 403, label: 'Shinx', types: ['electric'], base: { hp: 45, atk: 65, def: 34, spd: 45 }, ability: 'swift' },
  luxio: { name: 'luxio', id: 404, label: 'Luxio', types: ['electric'], base: { hp: 60, atk: 85, def: 49, spd: 60 }, ability: 'swift' },
  luxray: { name: 'luxray', id: 405, label: 'Luxray', types: ['electric'], base: { hp: 80, atk: 120, def: 79, spd: 70 }, ability: 'swift', coverage: 'ice' },
  tympole: { name: 'tympole', id: 535, label: 'Tympole', types: ['water'], base: { hp: 50, atk: 50, def: 40, spd: 64 }, ability: 'regen' },
  palpitoad: { name: 'palpitoad', id: 536, label: 'Palpitoad', types: ['water', 'ground'], base: { hp: 75, atk: 65, def: 55, spd: 69 }, ability: 'regen' },
  seismitoad: { name: 'seismitoad', id: 537, label: 'Seismitoad', types: ['water', 'ground'], base: { hp: 105, atk: 95, def: 75, spd: 74 }, ability: 'regen', coverage: 'poison' },
  zubat: { name: 'zubat', id: 41, label: 'Zubat', types: ['poison', 'flying'], base: { hp: 40, atk: 45, def: 35, spd: 55 }, ability: 'drain' },
  golbat: { name: 'golbat', id: 42, label: 'Golbat', types: ['poison', 'flying'], base: { hp: 75, atk: 80, def: 70, spd: 90 }, ability: 'drain' },
  crobat: { name: 'crobat', id: 169, label: 'Crobat', types: ['poison', 'flying'], base: { hp: 85, atk: 90, def: 80, spd: 130 }, ability: 'drain', coverage: 'fighting' },
  geodude: { name: 'geodude', id: 74, label: 'Geodude', types: ['rock', 'ground'], base: { hp: 40, atk: 80, def: 100, spd: 20 }, ability: 'shell' },
  graveler: { name: 'graveler', id: 75, label: 'Graveler', types: ['rock', 'ground'], base: { hp: 55, atk: 95, def: 115, spd: 35 }, ability: 'shell' },
  golem: { name: 'golem', id: 76, label: 'Golem', types: ['rock', 'ground'], base: { hp: 80, atk: 120, def: 130, spd: 45 }, ability: 'shell', coverage: 'fire' },
  magikarp: { name: 'magikarp', id: 129, label: 'Magikarp', types: ['water'], base: { hp: 20, atk: 10, def: 55, spd: 80 }, ability: 'intimidate' },
  gyarados: { name: 'gyarados', id: 130, label: 'Gyarados', types: ['water', 'flying'], base: { hp: 95, atk: 125, def: 79, spd: 81 }, ability: 'intimidate', coverage: 'dark' },
  magnemite: { name: 'magnemite', id: 81, label: 'Magnemite', types: ['electric', 'steel'], base: { hp: 25, atk: 35, def: 70, spd: 45 }, ability: 'focus' },
  magneton: { name: 'magneton', id: 82, label: 'Magneton', types: ['electric', 'steel'], base: { hp: 50, atk: 60, def: 95, spd: 70 }, ability: 'focus' },
  scyther: { name: 'scyther', id: 123, label: 'Scyther', types: ['bug', 'flying'], base: { hp: 70, atk: 110, def: 80, spd: 105 }, ability: 'swift' },
  scizor: { name: 'scizor', id: 212, label: 'Scizor', types: ['bug', 'steel'], base: { hp: 70, atk: 130, def: 100, spd: 65 }, ability: 'swift', coverage: 'fighting' },
  sandshrew: { name: 'sandshrew', id: 27, label: 'Sandshrew', types: ['ground'], base: { hp: 50, atk: 75, def: 85, spd: 40 }, ability: 'shell' },
  sandslash: { name: 'sandslash', id: 28, label: 'Sandslash', types: ['ground'], base: { hp: 75, atk: 100, def: 110, spd: 65 }, ability: 'shell', coverage: 'rock' },
  snorunt: { name: 'snorunt', id: 361, label: 'Snorunt', types: ['ice'], base: { hp: 50, atk: 50, def: 50, spd: 50 }, ability: 'lucky' },
  glalie: { name: 'glalie', id: 362, label: 'Glalie', types: ['ice'], base: { hp: 80, atk: 80, def: 80, spd: 80 }, ability: 'lucky', coverage: 'dark' },
  riolu: { name: 'riolu', id: 447, label: 'Riolu', types: ['fighting'], base: { hp: 40, atk: 70, def: 40, spd: 60 }, ability: 'focus' },
  lucario: { name: 'lucario', id: 448, label: 'Lucario', types: ['fighting', 'steel'], base: { hp: 70, atk: 110, def: 70, spd: 90 }, ability: 'focus', coverage: 'fire' },
  tauros: { name: 'tauros', id: 128, label: 'Tauros', types: ['normal'], base: { hp: 75, atk: 100, def: 95, spd: 110 }, ability: 'intimidate' },
  snorlax: { name: 'snorlax', id: 143, label: 'Snorlax', types: ['normal'], base: { hp: 160, atk: 110, def: 65, spd: 30 }, ability: 'regen' },
  lapras: { name: 'lapras', id: 131, label: 'Lapras', types: ['water', 'ice'], base: { hp: 130, atk: 85, def: 80, spd: 60 }, ability: 'shell' },
  aerodactyl: { name: 'aerodactyl', id: 142, label: 'Aerodactyl', types: ['rock', 'flying'], base: { hp: 80, atk: 105, def: 65, spd: 130 }, ability: 'swift', coverage: 'fire' },
  skarmory: { name: 'skarmory', id: 227, label: 'Skarmory', types: ['steel', 'flying'], base: { hp: 65, atk: 80, def: 140, spd: 70 }, ability: 'shell' },
  absol: { name: 'absol', id: 359, label: 'Absol', types: ['dark'], base: { hp: 65, atk: 130, def: 60, spd: 75 }, ability: 'lucky', coverage: 'fighting' },
  mawile: { name: 'mawile', id: 303, label: 'Mawile', types: ['steel', 'fairy'], base: { hp: 50, atk: 85, def: 85, spd: 50 }, ability: 'intimidate' },
};

/** Maps each basic form to its full evolution line. */
export const BASE_TO_CHAIN: Record<string, readonly string[]> = {
  charmander: ['charmander', 'charmeleon', 'charizard'],
  squirtle: ['squirtle', 'wartortle', 'blastoise'],
  bulbasaur: ['bulbasaur', 'ivysaur', 'venusaur'],
  treecko: ['treecko', 'grovyle', 'sceptile'],
  chimchar: ['chimchar', 'monferno', 'infernape'],
  piplup: ['piplup', 'prinplup', 'empoleon'],
  ralts: ['ralts', 'kirlia', 'gardevoir'],
  gastly: ['gastly', 'haunter', 'gengar'],
  dratini: ['dratini', 'dragonair', 'dragonite'],
  larvitar: ['larvitar', 'pupitar', 'tyranitar'],
  beldum: ['beldum', 'metang', 'metagross'],
  trapinch: ['trapinch', 'vibrava', 'flygon'],
  swinub: ['swinub', 'piloswine', 'mamoswine'],
  machop: ['machop', 'machoke', 'machamp'],
  abra: ['abra', 'kadabra', 'alakazam'],
  shinx: ['shinx', 'luxio', 'luxray'],
  tympole: ['tympole', 'palpitoad', 'seismitoad'],
  zubat: ['zubat', 'golbat', 'crobat'],
  geodude: ['geodude', 'graveler', 'golem'],
  magikarp: ['magikarp', 'gyarados'],
  magnemite: ['magnemite', 'magneton'],
  scyther: ['scyther', 'scizor'],
  sandshrew: ['sandshrew', 'sandslash'],
  snorunt: ['snorunt', 'glalie'],
  riolu: ['riolu', 'lucario'],
  tauros: ['tauros'],
  snorlax: ['snorlax'],
  lapras: ['lapras'],
  aerodactyl: ['aerodactyl'],
  skarmory: ['skarmory'],
  absol: ['absol'],
  mawile: ['mawile'],
};

/** All draftable basic forms. */
export const DRAFT_POOL: readonly string[] = ['charmander', 'squirtle', 'bulbasaur', 'treecko', 'chimchar', 'piplup', 'ralts', 'gastly', 'dratini', 'larvitar', 'beldum', 'trapinch', 'swinub', 'machop', 'abra', 'shinx', 'tympole', 'zubat', 'geodude', 'magikarp', 'magnemite', 'scyther', 'sandshrew', 'snorunt', 'riolu', 'tauros', 'snorlax', 'lapras', 'aerodactyl', 'skarmory', 'absol', 'mawile'];
